project_id = "jnqyihdbohdscpnjciav"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true

[functions.moderate-message]
verify_jwt = false

[functions.moderate-proposal]
verify_jwt = false

[functions.escrow-release]
verify_jwt = false

[functions.daily-job-notifications]
verify_jwt = false

[functions.paystack-charge]
verify_jwt = false

[functions.paystack-transfer]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false
